config/routes.rb
Rails.application.routes.draw do
  root "authentications#new"

  resources :authentications, only: [:new, :create]

  resources :users, only: [:index, :edit, :update, :create, :new, :destroy]
  resources :appointments, only: [:index, :new,:edit, :update, :create, :destroy]
  resources :pets, only: [:edit, :update, :new, :create]

  match 'signout', to: 'authentications#destroy', via: 'delete'

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base

  validates_presence_of :date_of_visit
  validate :valid_date?

  belongs_to :customer, class_name: "User"
  belongs_to :pet
  belongs_to :doctor, class_name: "User"#, -> { where("users.role = ?", :doctor) }

  private
  def valid_date?
    unless self.date_of_visit && (self.date_of_visit.to_date > Date.current)
      errors.add(:date_of_visit, (errors[:date_of_visit] || "Date should be in future"))
    end
  end
end

app/models/pet.rb
class Pet < ActiveRecord::Base

  validates_presence_of :age, :weight, :breed, :name

  validates_length_of :name, maximum: 35
  validates_length_of :breed, maximum: 35

  validates_inclusion_of :pet_type, in: %w(dog cat bird)

  has_many :appointments
  belongs_to :customer, class_name: "User"

  def next_appointment
    appointments.where(customer_id: self.customer_id).where("appointments.date_of_visit > ?",Date.current).first
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  validates_presence_of :name
  validates_length_of :name, maximum: 35

  validates_length_of :zip, minimum: 5
  validates_numericality_of :years_in_practice, greater_than_or_equal_to: 1, less_than_or_equal_to: 100, if: Proc.new { |user| user.role == 'doctor' }

  validates_inclusion_of :role, in: %w(doctor receptionist customer)

  has_many :appointments
  has_many :pets_through_appointments, through: :appointments
  has_many :pets

  def self.authenticate_user(params)
    where(email: params[:email], password: params[:password]).last
  end

  def access_for_doctors
    self.owner? ? User.where(role: 'doctor') : []
  end

  def appointments
    if self.role == 'doctor'
      Appointment.where(doctor_id: self.id)
    elsif self.role == 'customer'
      Appointment.where(customer_id: self.id)
    end
  end

  def pets
    Pet.where(customer_id: self.id)
  end

  def pets_through_appointments
    if self.role == 'doctor'
      Pet.joins(:appointments).where(appointments: {doctor_id: self.id})
    elsif self.role == 'customer'
      Pet.joins(:appointments).where(appointments: {customer_id: self.id})
    elsif self.role == 'receptionist'
      Pet.joins(:appointments).where(appointments: {customer_id: self.id})
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :c_user

  def c_user
    @current_user ||= User.find(session[:current_user]) if session[:current_user]
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController

  def index
    @app_creates = @current_user.role == 'receptionist' ? Appointment.where("date_of_visit > ?", Date.current) : []
  end

  def new
    @app_create = Appointment.new
  end

  def show
    @app_creates = Appointment.all
  end

  def edit
    @app_create = Appointment.find(params[:id])
  end

  def update
    @app_create = Appointment.find(params[:id])
    if @app_create.update_attributes(appointment_params)
      flash[:success] = "Successfully updated"
      redirect_to users_path
    else
      flash[:error] = "Something went wrong"
      render :edit
    end
  end

  def create
    @app_create = Appointment.new(appointment_params)
    if @app_create.save
      flash[:success] = "Successfully Created an Appointment"
      redirect_to users_path
    else
      flash[:error] = "Something went wrong"
      render :new
    end

    def destroy
      @app_create= Appointment.find(params[:id])
      @app_create.destroy
      redirect_to :back
    end

  end

  private
  def appointment_params
    params.require(:appointment).permit(:date_of_visit, :customer_id,:pet_id, :requires_reminder, :reason_for_visit, :doctor_id)
  end

end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController

  def new
    redirect_to users_path if session[:current_user]
  end

  def create
    @current_user = User.authenticate_user(params[:auth_params])

    if params[:auth_params] && @current_user
      session[:current_user] = @current_user.id
        flash[:success] = "Successfully logged in"
        redirect_to users_path
    else
      flash[:error] = 'Please check credentials'
      redirect_to new_authentication_path
    end
  end

  def destroy
    session[:current_user] = nil
    redirect_to new_authentication_path
  end

end

app/controllers/pets_controller.rb
class PetsController < ApplicationController

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    if @pet.save
      flash[:success] = "Successfully updated"
      redirect_to users_path
    else
      flash[:error] = "Something went wrong"
      render :new
    end
  end

  def edit
    @pet = Pet.find(params[:id])
  end

  def update
    @pet = Pet.find(params[:id])
    if @pet.update_attributes(pet_params)
      flash[:success] = "Successfuly updated"
      redirect_to users_path
    else
      flash[:error] = "Please check for errors"
      render :edit
    end
  end

  private
  def pet_params
    params.require(:pet).permit(:name, :pet_type, :breed, :age, :weight, :date_of_last_visit)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @current_user = User.find(session[:current_user])
    @doctors = @current_user.access_for_doctors
    @appointment_pets = @current_user.pets_through_appointments.uniq
    @all_appointments = @current_user.role == 'receptionist' ? Appointment.where("date_of_visit > ?", Date.current) : []
    @pets = @current_user.pets
  end

  def edit
    @doctor = User.find(params[:id])
  end

  def new
    @doctor = User.new
  end

  def create
    @doctor = User.new(user_params)
    if @doctor.save
      flash[:success] = "Successfully updated"
      redirect_to action: :index
    else
      flash[:error] = "Something went wrong"
      render :new
    end
  end

  def destroy
    @doctor= User.find(params[:id])
    session[:current_user] = nil
  end

  def list
    @doctor = appointment_pets.find(:all)
  end

  def destroy
    appointment = @all_appointments.find_by_id(params[:id])
    appointment.destroy
    redirect_to :back
  end

  def update
    @doctor = User.find(params[:id])
    if @doctor.update_attributes(user_params)
      flash[:success] = "Successfully updated"
      redirect_to action: :index
    else
      flash[:error] = "Something went wrong"
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :address, :city, :state, :zip, :school_name, :role, :years_in_practice,:owner, :email, :password)
  end

  # def user1_params
  #   params.require(:user).permit(:name, :address, :city, :state, :zip, :school_name, :role, :years_in_practice,:owner, :email, :password)
  # end

end

app/helpers/application_helper.rb
#application helper
module ApplicationHelper
end

app/views/appointments/_form.html.erb
<% if @app_create.errors.any? %>
  <div class="row">
    <div class="alert alert-danger col-md-8 col-md-offset-2 left">
      <h5>Please correct the following errors:</h5>
      <ul>
        <% @app_create.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>
<div class="row well">
  <div class="col-md-4 col-md-offset-4 left">
    <%= simple_form_for @app_create do |f| %>
    <br><br>
      <%= f.input :date_of_visit, as: :date %><br>
      <%= f.input :customer_id do %>
        <%= f.select :customer_id, User.where(role: :customer).map { |u| [u.name, u.id] }%><br>
      <% end %>
      <%= f.input :pet_id do %>
        <%= f.select :pet_id, Pet.all.map { |pet| [pet.name, pet.id] }%><br>
      <% end %>
      <%= f.input :doctor_id do %>
        <%= f.select :doctor_id, User.where(role: :doctor).map { |user| [user.name, user.id] }%><br>
      <% end %>
      <%= f.input :requires_reminder %><br>
      <%= f.input :reason_for_visit%><br>

      <%= f.submit(@app_create.new_record? ? 'Create Appointment' : 'Update Appointment' , class: 'btn btn-success', id: 'button') %>
      <%= link_to 'Back', :back, class: 'btn btn-success', id: 'button' %>
    <% end %>
  </div>
</div>

app/views/appointments/edit.html.erb
<h2>Edit Appointment</h2>

<%= render 'form' %>

app/views/appointments/new.html.erb
<h1>Create a Appointment </h1>

<%= render 'form' %>

app/views/authentications/new.html.erb
<div class="row jumbotron">
  <div class="col-md-4 col-md-offset-4 left">
    <%= form_tag :authentications do %>
      <div id="form-gap">
        <%= label_tag :Email %>
        <%= text_field :auth_params, :email %>
      </div>

      <div id="form-gap">
        <%= label_tag :Password %>
        <%= password_field :auth_params, :password %>
      </div>

      <div id="form-gap">
        <%= submit_tag 'Login', class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_flashes.html.erb
<div class="container">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %>
        <a class="close" data-dismiss="alert">&#215;</a>
      </div>
    <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer class="navbar navbar-default navbar-fixed-bottom">
  <div class="container">
    <p id= "copy-right">&copy; Srinivas Vet Practice 2016</p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-default">
  <div class="container">
    <%= link_to "Veterinary Practice", '', class: "btn btn-lg btn-success", id: "logo" %>
    <% if session[:current_user] %>
      <div class="nav-item btn btn-default btn-danger">
        Logged in as: <%= c_user.name %> (<%= c_user.owner? ? 'owner' : c_user.role %>)
      </div>
      <div class='pull-right'>
        <div class="nav-item btn btn-default btn-warning">
          <%= link_to "Home", users_path, method: :get if session[:current_user] %>
        </div>
        <div class="nav-item btn btn-default btn-warning">
          <%= link_to "Sign out", signout_path, :method => :delete if session[:current_user] %>
        </div>
      </div>
    <% end %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VeterniaryPractice</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <%= render "layouts/flashes" %>
  <div class="container center">
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/pets/_form.html.erb
<% if @pet.errors.any? %>
  <div class="row">
    <div class="alert alert-danger col-md-8 col-md-offset-2 left">
      <h5>Please correct the following errors:</h5>
      <ul>
        <% @pet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>
<div class="row well">
  <div class="col-md-8 col-md-offset-2 left">
    <%= form_for @pet do |f| %>
      <div id="form-gap">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>
      <div id="form-gap">
        <%= f.label :'Pet Type' %>
        <%= f.select :pet_type, options_for_select( %w[dog cat bird]) %>
      </div>
      <div id="form-gap">
        <%= f.label :Breed %>
        <%= f.text_field :breed %>
      </div>
      <div id="form-gap">
        <%= f.label :Age %>
        <%= f.text_field :age %>
      </div>
      <div id="form-gap">
        <%= f.label :Weight %>
        <%= f.text_field :weight %>
      </div>
      <div id="form-gap">
        <%= f.label :'Date of Visit' %>
        <%= f.text_field :date_of_last_visit, as: :date %>
      </div>
      <%= f.submit(@pet.new_record? ? "Create New Pet" : "Update Pet Info" , class: 'btn btn-success', id: 'button') %>
      <%= link_to 'Back', :back, class: 'btn btn-success', id: 'button' %>

    <% end %>
  </div>
</div>

app/views/pets/edit.html.erb
<%= render 'form' %>

app/views/pets/new.html.erb
<h2>New Pet Details</h2>
<%= render 'form' %>

app/views/users/_form.html.erb
<% if @doctor.errors.any? %>
  <div class="row">
    <div class="alert alert-danger col-md-8 col-md-offset-2 left">
      <h5>Please correct the following errors:</h5>
      <ul>
        <% @doctor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>
<div class="row well">
  <div class="col-md-8 col-md-offset-2 left">
    <%= form_for @doctor do |f| %>
      <div id="form-gap">
        <%= f.label :role %>
        <%= f.select :role, options_for_select( %w[doctor customer receptionist]) %>
      </div>
      <div id="form-gap">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>
      <div id="form-gap">
        <%= f.label :address %>
        <%= f.text_field :address %>
      </div>
      <div id="form-gap">
        <%= f.label :city %>
        <%= f.text_field :city %>
      </div>
      <div id="form-gap">
        <%= f.label :state %>
        <%= f.text_field :state %>
      </div>
      <div id="form-gap">
        <%= f.label :zip %>
        <%= f.text_field :zip %>
      </div>
      <div id="form-gap">
        <%= f.label :school_name %>
        <%= f.text_field :school_name %>
      </div>
      <div id="form-gap">
        <%= f.label :years_in_practice %>
        <%= f.text_field :years_in_practice %>
      </div>
      <div id="form-gap">
        <%= f.label :email %>
        <%= f.text_field :email %>
      </div>
      <div id="form-gap">
        <%= f.label :password %>
        <%= f.password_field :password %>
      </div>
      <%= f.submit(@doctor.new_record? ? "Create User" : "Update doctor", class: 'btn btn-success', id: 'button') %>
      <%= link_to 'Back', :back, class: 'btn btn-success', id: 'button' %>

    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/index.html.erb
<% if @current_user.owner? %>
<div class='left'>
  <h2>Doctors List</h2>
</div>
<div class="jumbotron">
  <table class='table table-condesed center'>
    <thead>
      <tr class='success'>
        <th>Name</th>
        <th>Role</th>
        <th>Address</th>
        <th>City</th>
        <th>State</th>
        <th>Zip</th>
        <th>School</th>
        <th>Years of Expe</th>
      </tr>
    </thead>
    <tbody>
      <% @doctors.each do |doctor| %>
        <tr>
          <td><%= link_to "#{doctor.name}", edit_user_path(doctor), id: 'doc-name' %></td>
          <td><%= doctor.role %></td>
          <td><%= doctor.address %></td>
          <td><%= doctor.city %></td>
          <td><%= doctor.state %></td>
          <td><%= doctor.zip %></td>
          <td><%= doctor.school_name %></td>
          <td><%= doctor.years_in_practice %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<div class="btn btn-lg btn-success">
  <span class="glyphicon glyphicon-plus"></span> <%= link_to "Create New Doctor", new_user_path %></br>
</div>
<% end %>
<% if @current_user.role == 'doctor' %></br>
  <h2  class='left'> List of Appointments you have </h2>
  <div class="left">
    <% @appointment_pets.each do |pet| %>
    <div class="well">
      Pet Name  : <%= pet.name %>
      <div class="pull-right">
        <%= link_to "Edit pet info", edit_pet_path(pet), class: "btn btn-sm btn-success" %></br>
      </div></br>
      Pet Type  : <%= pet.pet_type %></br>
      Pet Breed : <%= pet.breed %> </br>
      Pet Age   : <%= pet.age %></br>
      Pet Weight: <%= pet.weight %></br>
      Pet Last Visit Date: <%= pet.date_of_last_visit %></br>
    </div>
    <% end %>
  </div>
<% elsif @current_user.role == 'receptionist' %>
<div class='left'>
  <%= link_to "Create Appointment", new_appointment_path, class: "btn btn-lg btn-success"  %></br>
  <% @all_appointments.each do |appointment| %>
    <div class='well'>
      Customer Name: <%= appointment.customer.name %>
      <div class="pull-right">
        <%= link_to 'Edit Appointment', edit_appointment_path(appointment), class: "btn btn-sm btn-success" %>
      </div></br>
      Pet Name: <%= appointment.pet.try(:name) %></br>
      Doctor Name: <%= appointment.doctor.try(:name) %></br>
      Date of next appointment: <%= appointment.date_of_visit %></br>
      Reason for visit: <%= appointment.reason_for_visit %>
    </div>
  <% end %>
  <%= link_to "Create Appointment", new_appointment_path, class: "btn btn-lg btn-success"  %>
</div>
<% elsif @current_user.role == 'customer' %>
  <h2> Your next Appointment </h2>
  <div class="left">
    <% @pets.each do |pet| %>
      <div class="well">
        Name: <%= pet.name %></br>
        Date of next appointment: <%= pet.date_of_next_visit %></br>
        Reason for visit: <%= pet.next_appointment.reason_for_visit %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/users/new.html.erb
<h2>Create a new User</h2>

<%= render 'form' %>